### ISSUE TITLE
who are we?

### ISSUE THREAD

**Issue by kbeckmann** [F-R-1-3-N-D-S/whois#1]

**Comment by connect192168** [comment]
Hi.
S (wire name) AKA M_T AKA Jacob AKA Shaun AKA Eric ,etc.
Twitter: @books_n_infosec 
I'm a purple teamer.
I'm a bookworm and an insomniac (but only sometimes).
P.S. I'm looking for entry-level SOC jobs in and around London.

That's just about it... I think.
